# -*- coding: utf-8 -*-
"""Final_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jlRpILst148QaKXAP4FvqQVLBZ9ysD_D
"""

!pip install Sastrawi

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory #import Indonesian Stemmer

# Import library yang dibutuhkan
import tweepy
import pandas as pd
import matplotlib.pyplot as plt
import re
import numpy as np
import datetime
import sqlite3

# Nama : Hario Prakoso
# Email : harioprakoso@yahoo.co.id

# Menyiapkan key untuk mengakses API twitter (jangan disebar ya om)
consumer_key = "XXXXXXXXXXXXXXXXXX"
consumer_secret = "XXXXXXXXXXXXXXXXXXX"
access_token = "XXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXX"
access_token_secret = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXX"


# Menentukan keyword yang akan dicari
keyword = "vaksin covid"

def update_data(consumer_key,consumer_secret,access_token,access_token_secret, keyword):
  auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
  auth.set_access_token(access_token, access_token_secret)
  api = tweepy.API(auth,wait_on_rate_limit=True)

  # Mengambil tweet pada 2 hari sebelumnya 
  date_since = dayBefore(2)
  new_search = keyword + " -filter:retweets"

  # Mencari tweet dengan api.search
  tweets = tweepy.Cursor(api.search, q=new_search, lang="id", 
                         since=date_since).items(-1)

  # Memasukkan data tweet ke dalam list pertama
  items = []
  for tweet in tweets:
    item = []
    item.append(tweet.id_str)
    item.append(tweet.user.screen_name)
    item.append(tweet.created_at.date())
    #append preproc tweet
    item.append (' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)", " ", tweet.text).split()))
    items.append(item)
    
  # Mengubah list menjadi dataframe
  hasil = pd.DataFrame(data=items, columns=['TweetID','User','Date','Tweet'])
  return hasil
  
def dayBefore(count):
    now = datetime.date.today()
    delta = datetime.timedelta(days=count)
    date_since = now - delta
    return date_since

def input_sql(df):
  database_name = "Final_project.db"
  create_table = '''CREATE TABLE IF NOT EXISTS tweet (
                            TweetID TEXT,
                            Username TEXT,
                            Date TEXT,
                            Tweet TEXT);'''
  insert_table = '''INSERT INTO tweet (TweetID, Username, Date, Tweet) values (?, ?, ?, ?);'''
  connection = sqlite3.connect(database_name)
  cursor = connection.cursor()
  cursor.execute(create_table)
  for i in range(len(df)-1):
    baris = df.loc[[i+1],:]
    try:
      TweetID = str(baris["TweetID"].values)
      Username = str(baris["User"].values)
      Date = str(baris["Date"].values[0])
      Tweet = str(baris["Tweet"].values)
      cursor.execute(insert_table, (TweetID, Username, Date, Tweet))
    except:
      continue
  connection.commit()
  cursor.close()
  connection.close()


def lihat_tabel():  
  # Membuka tabel ke dataframe
  connection = sqlite3.connect('Final_project.db')
  cursor=connection.cursor()
  cursor.execute("SELECT * FROM TWEET WHERE Date >= ? and Date <= ?", (tglawal,tglakhir))
  result = cursor.fetchall()
  cursor.close()
  print(result)


def lihat_sentiment():  
  # Membuka tabel ke dataframe
  connection = sqlite3.connect('Final_project.db')
  data1 = pd.read_sql_query("SELECT * FROM sentimen", connection)
  data2= data1[(data1['Date'] >= tglawal) & (data1['Date'] <= tglakhir)]
  return data2

def visualisasi(data):
  labels, counts = np.unique(data["Sentiment"], return_counts=True)
  plt.title('Sentiment Analysis pada Twitter untuk Final Project')
  plt.bar(labels, counts, align='center')
  plt.xlabel('Nilai Sentiment')
  plt.ylabel('Frekuensi Sentiment')
  plt.show()

  print("Nilai rata-rata: "+str(np.mean(data["Sentiment"])))
  print("Angka tengah/ Median: "+str(np.median(data["Sentiment"])))
  print("Std: "+str(np.std(data["Sentiment"])))


def input_sentiment(df):
  items = data['Tweet'].tolist()
  items = [s.strip('[]') for s in items]
  items = [s.strip("'") for s in items]
  items = [x.lower() for x in items]

  pos_list= open("./kata_positif.txt","r")
  pos_kata = pos_list.readlines()
  neg_list= open("./kata_negatif.txt","r")
  neg_kata = neg_list.readlines()
  
  S=[]

  for item in items:
    count_p = 0
    count_n = 0
    for kata_pos in pos_kata:
      if kata_pos.strip() in item:
        count_p +=1
    
    for kata_neg in neg_kata:
      if kata_neg.strip() in item:
        count_n +=1
    
    S.append(count_p - count_n)
  
  data['Sentiment'] = S
  database_name = "Final_project.db"

  create_table = '''CREATE TABLE IF NOT EXISTS sentimen (
                            TweetID TEXT,
                            Username TEXT,
                            Date TEXT,
                            Tweet TEXT,
                            Sentiment INTEGER);'''
  insert_table = '''INSERT INTO sentimen (TweetID, Username, Date, Tweet, Sentiment) values (?, ?, ?, ?, ?);'''
  connection = sqlite3.connect(database_name)
  cursor = connection.cursor()
  cursor.execute(create_table)
  for i in range(len(df)-1):
    cursor = connection.cursor()
    baris = df.loc[[i+1],:]
    TweetID = str(baris["TweetID"].values)
    Username = str(baris["Username"].values)
    Date = str(baris["Date"].values[0])
    Tweet = str(baris["Tweet"].values)
    Sentiment = int(baris["Sentiment"].values)
    cursor.execute(insert_table,(TweetID, Username, Date, Tweet, Sentiment))
  connection.commit()
  cursor.close()
  connection.close()

while 1:  
  print('Apa yang ingin anda lakukan?\n\t1.Update Data\n\t2.Update Nilai Sentiment\n\t3.Lihat Data\n\t4.Visualisasi\n\t5.Keluar')
  x = input()
  if x == '1':
    df = update_data(consumer_key,consumer_secret,access_token,access_token_secret,keyword)
    input_sql(df)

  elif x == '2':
    connection = sqlite3.connect('Final_project.db')
    data = pd.read_sql_query("SELECT * FROM tweet", connection)
    input_sentiment(data)

  elif x == '3':
    tglawal = input('Tanggal Awal (format: 2020-09-24): ')
    tglahir = input('Tanggal Akhir (format: 2020-09-30): ')
    lihat_tabel()

  elif x == '4':
    tglawal = input('Tanggal Awal (format: 2020-09-24): ')
    tglahir = input('Tanggal Akhir (format: 2020-09-30): ')
    data1=lihat_sentiment()
    visualisasi(data1)

  elif x == '5':
    break

from google.colab import files
files.download('Final_project.db')

